baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "Erin Clerico"
theme = ["erin-clerico-hugo-bootstrap", "vanilla-bootstrap-hugo-theme", "photoswipe-portfolio"]

# Navbar

[menu]
[[menu.main]]
    identifier = "home"
    name = "home"
    url = "/"
    weight = 0
[[menu.main]]
    identifier = "portfolio"
    name = "portfolio"
    url = "/portfolio/"
    weight = 20

# Deployment config

[deployment]
# By default, files are uploaded in an arbitrary order.
# Files that match the regular expressions in the "Order" list
# will be uploaded first, in the listed order.
order = [".jpg$", ".gif$"]


[[deployment.targets]]
name = "aws-s3"


# S3; see https://gocloud.dev/howto/blob/#s3
# For S3-compatible endpoints, see https://gocloud.dev/howto/blob/#s3-compatible
URL = "s3://clerico.com?region=us-west-1"

# ... add more [[deployment.targets]] sections ...


# [[deployment.matchers]] configure behavior for files that match the Pattern.
# Samples:

[[deployment.matchers]]
#  Cache static assets for 1 year.
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true
